version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: service-book-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: car_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
